# Generated by Django 3.0.4 on 2020-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200319_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
