# Generated by Django 3.0.4 on 2020-03-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200320_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_admin',
            new_name='is_active',
        ),
    ]
